[package]
name = "twilight-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
dotenv = "0.15.0"
env_logger = "0.11.5"
fluent = "0.16.1"
poise = "0.6.1"
poise_macros = "0.6.1"
tokio = { version = "1.40.0", features = ["full"] }
